import { Article } from '../state/blog';

export function formatPriceWithComma(value: number) {
  return value
    ?.toFixed(2)
    .replace(/\d(?=(\d{3})+\.)/g, '$&,')
    .replace(/\.00$/, '');
}
export const articles: Article[] = [
  {
    type_of: 'article',
    id: 1,
    title: 'Introduction to React 18',
    description: 'A comprehensive guide to the latest features in React 18.',
    readable_publish_date: 'Feb 1, 2024',
    slug: 'introduction-to-react-18',
    path: '/react/introduction-to-react-18',
    url: 'https://example.com/react/introduction-to-react-18',
    comments_count: 12,
    public_reactions_count: 45,
    collection_id: null,
    published_timestamp: '2024-02-01T12:00:00Z',
    language: 'en',
    subforem_id: 101,
    positive_reactions_count: 40,
    cover_image: 'https://example.com/images/react-18.jpg',
    social_image: 'https://example.com/images/react-18-social.jpg',
    canonical_url: 'https://example.com/react/introduction-to-react-18',
    created_at: '2024-01-31T10:00:00Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2024-02-01T12:00:00Z',
    last_comment_at: '2024-02-02T14:30:00Z',
    reading_time_minutes: 8,
    tag_list: ['React', 'JavaScript', 'Web Development'],
    tags: 'React, JavaScript, Web Development',
    user: {
      name: 'John Doe',
      username: 'johndoe',
      twitter_username: 'johndoe_dev',
      github_username: 'johndoe',
      user_id: 1001,
      website_url: 'https://johndoe.dev',
      profile_image: 'https://example.com/profiles/johndoe.jpg',
      profile_image_90: 'https://example.com/profiles/johndoe-90.jpg',
    },
    flare_tag: {
      name: 'React',
      bg_color_hex: '#61dafb',
      text_color_hex: '#000000',
    },
  },
  {
    type_of: 'article',
    id: 2,
    title: 'Understanding TypeScript Generics',
    description: 'A deep dive into generics in TypeScript and how to use them effectively.',
    readable_publish_date: 'Feb 3, 2024',
    slug: 'typescript-generics-guide',
    path: '/typescript/typescript-generics-guide',
    url: 'https://example.com/typescript/typescript-generics-guide',
    comments_count: 8,
    public_reactions_count: 30,
    collection_id: null,
    published_timestamp: '2024-02-03T15:00:00Z',
    language: 'en',
    subforem_id: 102,
    positive_reactions_count: 28,
    cover_image: 'https://example.com/images/ts-generics.jpg',
    social_image: 'https://example.com/images/ts-generics-social.jpg',
    canonical_url: 'https://example.com/typescript/typescript-generics-guide',
    created_at: '2024-02-02T11:00:00Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2024-02-03T15:00:00Z',
    last_comment_at: '2024-02-04T10:45:00Z',
    reading_time_minutes: 10,
    tag_list: ['TypeScript', 'Programming', 'Web Development'],
    tags: 'TypeScript, Programming, Web Development',
    user: {
      name: 'Jane Smith',
      username: 'janesmith',
      twitter_username: 'janesmith_dev',
      github_username: 'janesmith',
      user_id: 1002,
      website_url: 'https://janesmith.dev',
      profile_image: 'https://example.com/profiles/janesmith.jpg',
      profile_image_90: 'https://example.com/profiles/janesmith-90.jpg',
    },
    flare_tag: {
      name: 'TypeScript',
      bg_color_hex: '#3178c6',
      text_color_hex: '#ffffff',
    },
  },
  {
    type_of: 'article',
    id: 3,
    title: 'Building Scalable Web Apps with Next.js',
    description: 'How to create scalable applications using Next.js and server-side rendering.',
    readable_publish_date: 'Feb 5, 2024',
    slug: 'scalable-web-apps-nextjs',
    path: '/nextjs/scalable-web-apps-nextjs',
    url: 'https://example.com/nextjs/scalable-web-apps-nextjs',
    comments_count: 15,
    public_reactions_count: 50,
    collection_id: null,
    published_timestamp: '2024-02-05T09:00:00Z',
    language: 'en',
    subforem_id: 103,
    positive_reactions_count: 47,
    cover_image: 'https://example.com/images/nextjs-scalable.jpg',
    social_image: 'https://example.com/images/nextjs-scalable-social.jpg',
    canonical_url: 'https://example.com/nextjs/scalable-web-apps-nextjs',
    created_at: '2024-02-04T08:00:00Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2024-02-05T09:00:00Z',
    last_comment_at: '2024-02-06T11:20:00Z',
    reading_time_minutes: 12,
    tag_list: ['Next.js', 'React', 'Web Development'],
    tags: 'Next.js, React, Web Development',
    user: {
      name: 'Michael Brown',
      username: 'michaelbrown',
      twitter_username: 'michaelbrown_dev',
      github_username: 'michaelbrown',
      user_id: 1003,
      website_url: 'https://michaelbrown.dev',
      profile_image: 'https://example.com/profiles/michaelbrown.jpg',
      profile_image_90: 'https://example.com/profiles/michaelbrown-90.jpg',
    },
    flare_tag: {
      name: 'Next.js',
      bg_color_hex: '#000000',
      text_color_hex: '#ffffff',
    },
  },
  {
    type_of: 'article',
    id: 4,
    title: 'CSS Grid vs Flexbox: Which One Should You Use?',
    description: 'A comparison between CSS Grid and Flexbox for layout design.',
    readable_publish_date: 'Feb 7, 2024',
    slug: 'css-grid-vs-flexbox',
    path: '/css/css-grid-vs-flexbox',
    url: 'https://example.com/css/css-grid-vs-flexbox',
    comments_count: 7,
    public_reactions_count: 20,
    collection_id: null,
    published_timestamp: '2024-02-07T14:00:00Z',
    language: 'en',
    subforem_id: 104,
    positive_reactions_count: 19,
    cover_image: 'https://example.com/images/css-grid-vs-flexbox.jpg',
    social_image: 'https://example.com/images/css-grid-vs-flexbox-social.jpg',
    canonical_url: 'https://example.com/css/css-grid-vs-flexbox',
    created_at: '2024-02-06T12:00:00Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2024-02-07T14:00:00Z',
    last_comment_at: '2024-02-08T15:30:00Z',
    reading_time_minutes: 6,
    tag_list: ['CSS', 'Frontend', 'Design'],
    tags: 'CSS, Frontend, Design',
    user: {
      name: 'Emily White',
      username: 'emilywhite',
      twitter_username: 'emilywhite_dev',
      github_username: 'emilywhite',
      user_id: 1004,
      website_url: 'https://emilywhite.dev',
      profile_image: 'https://example.com/profiles/emilywhite.jpg',
      profile_image_90: 'https://example.com/profiles/emilywhite-90.jpg',
    },
    flare_tag: {
      name: 'CSS',
      bg_color_hex: '#1572b6',
      text_color_hex: '#ffffff',
    },
  },
  {
    type_of: 'article',
    id: 5,
    title: 'CSS Grid vs Flexbox: Which One Should You Use?',
    description: 'A comparison between CSS Grid and Flexbox for layout design.',
    readable_publish_date: 'Feb 7, 2024',
    slug: 'css-grid-vs-flexbox',
    path: '/css/css-grid-vs-flexbox',
    url: 'https://example.com/css/css-grid-vs-flexbox',
    comments_count: 7,
    public_reactions_count: 20,
    collection_id: null,
    published_timestamp: '2024-02-07T14:00:00Z',
    language: 'en',
    subforem_id: 104,
    positive_reactions_count: 19,
    cover_image: 'https://example.com/images/css-grid-vs-flexbox.jpg',
    social_image: 'https://example.com/images/css-grid-vs-flexbox-social.jpg',
    canonical_url: 'https://example.com/css/css-grid-vs-flexbox',
    created_at: '2024-02-06T12:00:00Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2024-02-07T14:00:00Z',
    last_comment_at: '2024-02-08T15:30:00Z',
    reading_time_minutes: 6,
    tag_list: ['CSS', 'Frontend', 'Design'],
    tags: 'CSS, Frontend, Design',
    user: {
      name: 'Emily White',
      username: 'emilywhite',
      twitter_username: 'emilywhite_dev',
      github_username: 'emilywhite',
      user_id: 1004,
      website_url: 'https://emilywhite.dev',
      profile_image: 'https://example.com/profiles/emilywhite.jpg',
      profile_image_90: 'https://example.com/profiles/emilywhite-90.jpg',
    },
    flare_tag: {
      name: 'CSS',
      bg_color_hex: '#1572b6',
      text_color_hex: '#ffffff',
    },
  },
  {
    type_of: 'article',
    id: 6,
    title: 'CSS Grid vs Flexbox: Which One Should You Use?',
    description: 'A comparison between CSS Grid and Flexbox for layout design.',
    readable_publish_date: 'Feb 7, 2024',
    slug: 'css-grid-vs-flexbox',
    path: '/css/css-grid-vs-flexbox',
    url: 'https://example.com/css/css-grid-vs-flexbox',
    comments_count: 7,
    public_reactions_count: 20,
    collection_id: null,
    published_timestamp: '2024-02-07T14:00:00Z',
    language: 'en',
    subforem_id: 104,
    positive_reactions_count: 19,
    cover_image: 'https://example.com/images/css-grid-vs-flexbox.jpg',
    social_image: 'https://example.com/images/css-grid-vs-flexbox-social.jpg',
    canonical_url: 'https://example.com/css/css-grid-vs-flexbox',
    created_at: '2024-02-06T12:00:00Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2024-02-07T14:00:00Z',
    last_comment_at: '2024-02-08T15:30:00Z',
    reading_time_minutes: 6,
    tag_list: ['CSS', 'Frontend', 'Design'],
    tags: 'CSS, Frontend, Design',
    user: {
      name: 'Emily White',
      username: 'emilywhite',
      twitter_username: 'emilywhite_dev',
      github_username: 'emilywhite',
      user_id: 1004,
      website_url: 'https://emilywhite.dev',
      profile_image: 'https://example.com/profiles/emilywhite.jpg',
      profile_image_90: 'https://example.com/profiles/emilywhite-90.jpg',
    },
    flare_tag: {
      name: 'CSS',
      bg_color_hex: '#1572b6',
      text_color_hex: '#ffffff',
    },
  },
];
